---
- name: Run terraform configuration
  ansible.builtin.shell: HOME_DIR={{ home_dir }} VAULT_TOKEN={{ transit_token }} bash "{{home_dir}}/scripts/init.sh" boundary
  delegate_to: localhost
  ignore_errors: true
  register: terraform_boundary

- name: Handle errors if occurred
  ansible.builtin.include_tasks: "{{handlers}}/fail_task.yml"
  vars:
    output: "{{ terraform_boundary }}"
